# Generated by Django 4.1 on 2022-09-05 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='recintos',
            name='id_recinto',
        ),
        migrations.RemoveField(
            model_name='vehiculos',
            name='id_vehiculo',
        ),
    ]
