# Generated by Django 4.1 on 2022-09-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0002_remove_empleados_id_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recintos',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='vehiculos',
            name='id_empleado',
        ),
    ]
