# Generated by Django 4.1 on 2022-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0003_remove_recintos_id_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='apellido_nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='dni',
            field=models.CharField(max_length=20, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fecha_nac',
            field=models.DateField(verbose_name='Fecha nacimiento'),
        ),
    ]
