# Generated by Django 4.1 on 2022-09-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0004_alter_empleados_apellido_nombre_alter_empleados_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='recinto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
