# Generated by Django 4.1 on 2022-09-16 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0005_alter_empleados_correo_alter_empleados_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_baja',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha baja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recintos',
            name='nombre_recinto',
            field=models.CharField(max_length=100, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='nombre_vehiculo',
            field=models.CharField(max_length=100, verbose_name='Nombre vehiculo'),
        ),
    ]
