# Generated by Django 4.1 on 2022-09-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0006_empleados_activo_empleados_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha baja'),
        ),
    ]
