# Generated by Django 4.1 on 2022-09-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0007_alter_empleados_fecha_baja'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
        migrations.RenameModel(
            old_name='Recintos',
            new_name='Recinto',
        ),
        migrations.RenameModel(
            old_name='Vehiculos',
            new_name='Vehiculo',
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterModelOptions(
            name='recinto',
            options={'verbose_name': 'recinto', 'verbose_name_plural': 'recintos'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'vehiculo', 'verbose_name_plural': 'vehiculos'},
        ),
    ]
