# Generated by Django 4.1 on 2022-09-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0008_rename_empleados_empleado_rename_recintos_recinto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados'),
        ),
    ]
