# Generated by Django 4.1 on 2022-09-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0009_alter_empleado_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recinto',
            new_name='Sector',
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'sector', 'verbose_name_plural': 'sectores'},
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='nombre_recinto',
            new_name='nombre_sector',
        ),
    ]
