# Generated by Django 4.1 on 2022-10-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0010_rename_recinto_sector_alter_sector_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='recinto',
        ),
        migrations.AddField(
            model_name='empleado',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionEmpleados.sector'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionEmpleados.vehiculo'),
        ),
    ]
